name: variables
run-name: ¡corriendo el workflow de variable!
on:
  workflow_dispatch:
env:
  DIA_DE_SEMANA: Lunes
jobs:
  saludo-variable:
    runs-on: ubuntu-latest
    env:
      SALUDO: Hola
    steps:
      - name: Saludar
        run: echo "$SALUDO, ${{ vars.NOMBRE }} $APELLIDO. hoy es $DIA_DE_SEMANA! año ${{ secrets.ANO }}"
        env:
           APELLIDO: Martinezr